
package vista;
import dao.EmpleadoDAO;
import modelo.Empleado;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;

public class VentanaPrincipal extends javax.swing.JFrame {
    private EmpleadoDAO empleadoDAO;
    private DefaultTableModel modeloTabla;
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName());

   public VentanaPrincipal() {
        initComponents(); // Esto lo genera NetBeans, inicializa tus botones y tabla
        this.setLocationRelativeTo(null); // Centra la ventana en la pantalla
        
        // Instanciamos nuestro DAO
        empleadoDAO = new EmpleadoDAO();
        
        // Inicializamos el modelo asociándolo a nuestra tabla del diseño
        modeloTabla = (DefaultTableModel) tablaEmpleados.getModel();
        
        // Configuramos los títulos de las columnas de la tabla
        String[] titulos = {"ID", "Nombre", "Departamento"};
        modeloTabla.setColumnIdentifiers(titulos);
        
        // Cargamos los datos por primera vez al abrir la aplicación
        cargarDatosTabla();
    }
    
    // Método para poblar la tabla leyendo la base de datos
    private void cargarDatosTabla() {
        // Limpiamos el modelo por si ya tenía filas cargadas antes
        modeloTabla.setRowCount(0); 
        
        // Invocamos consultarTodos() de nuestro DAO
        ArrayList<Empleado> lista = empleadoDAO.consultarTodos();
        for (Empleado emp : lista) {
            // Añadimos cada empleado como una fila en el JTable
            modeloTabla.addRow(new Object[]{
                emp.getId(),
                emp.getNombre(),
                emp.getDepartamento()
            });
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tablaEmpleados = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtId = new javax.swing.JTextField();
        txtDepartamento = new javax.swing.JTextField();
        btnModificar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnAgregar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tablaEmpleados.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        tablaEmpleados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tablaEmpleados.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaEmpleadosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tablaEmpleados);

        jLabel1.setText("ID");

        txtNombre.addActionListener(this::txtNombreActionPerformed);

        jLabel2.setText("Nombre");

        jLabel3.setText("Departamento");

        txtId.setEditable(false);
        txtId.addActionListener(this::txtIdActionPerformed);

        txtDepartamento.addActionListener(this::txtDepartamentoActionPerformed);

        btnModificar.setText("Modificar");
        btnModificar.addActionListener(this::btnModificarActionPerformed);

        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(this::btnEliminarActionPerformed);

        btnAgregar.setText("Agregar");
        btnAgregar.addActionListener(this::btnAgregarActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnEliminar)
                            .addComponent(btnModificar)
                            .addComponent(btnAgregar)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(32, 32, 32)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtNombre, javax.swing.GroupLayout.DEFAULT_SIZE, 114, Short.MAX_VALUE)
                                    .addComponent(txtId)))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtDepartamento, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 114, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 399, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(58, 58, 58))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtDepartamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(57, 57, 57)
                .addComponent(btnModificar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(153, Short.MAX_VALUE))
            .addComponent(jScrollPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreActionPerformed

    private void txtIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdActionPerformed

    private void txtDepartamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDepartamentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDepartamentoActionPerformed

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
        // TODO add your handling code here:
        // 1. Recoger los nuevos valores de los JTextField (Paso 5 del PDF)
    int id = Integer.parseInt(txtId.getText());
    String nombre = txtNombre.getText();
    String departamento = txtDepartamento.getText();

    // 2. Crear un objeto Empleado con los datos capturados
    Empleado emp = new Empleado(id, nombre, departamento);

    // 3. Pasarlo al método modificar del DAO
    if (empleadoDAO.modificar(emp)) {
        javax.swing.JOptionPane.showMessageDialog(this, "Empleado modificado con éxito.");
        
        // 4. Refrescar la tabla y limpiar los campos de texto
        cargarDatosTabla();
        txtId.setText("");
        txtNombre.setText("");
        txtDepartamento.setText("");
    } else {
        javax.swing.JOptionPane.showMessageDialog(this, "Error al modificar el empleado.");
    }
    }//GEN-LAST:event_btnModificarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        // TODO add your handling code here:
        // 1. Recoger únicamente el ID seleccionado (Paso 6 del PDF)
    String idText = txtId.getText();
    
    if (!idText.isEmpty()) {
        int id = Integer.parseInt(idText);
        
        // 2. Pasarlo al método eliminar del DAO
        if (empleadoDAO.eliminar(id)) {
            javax.swing.JOptionPane.showMessageDialog(this, "Empleado eliminado con éxito.");
            
            // 3. Refrescar la tabla y limpiar las cajas de texto
            cargarDatosTabla();
            txtId.setText("");
            txtNombre.setText("");
            txtDepartamento.setText("");
        } else {
            javax.swing.JOptionPane.showMessageDialog(this, "Error al eliminar el empleado.");
        }
    } else {
        javax.swing.JOptionPane.showMessageDialog(this, "Seleccione un empleado de la tabla para eliminar.");
    }
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        // TODO add your handling code here:
        // 1. Capturar los datos de los JTextField (El ID no se pasa porque es AUTO_INCREMENT)
    String nombre = txtNombre.getText();
    String departamento = txtDepartamento.getText();

    if (!nombre.isEmpty() && !departamento.isEmpty()) {
        Empleado nuevoEmp = new Empleado(nombre, departamento);
        
        // 2. Invocar el método insertar del DAO
        if (empleadoDAO.insertar(nuevoEmp)) {
            javax.swing.JOptionPane.showMessageDialog(this, "Empleado agregado con éxito.");
            cargarDatosTabla(); // Refresca la lista visual
            
            // Limpiar campos
            txtNombre.setText("");
            txtDepartamento.setText("");
        } else {
            javax.swing.JOptionPane.showMessageDialog(this, "Error al guardar el empleado.");
        }
    } else {
        javax.swing.JOptionPane.showMessageDialog(this, "Por favor complete Nombre y Departamento.");
    }
    }//GEN-LAST:event_btnAgregarActionPerformed

    private void tablaEmpleadosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaEmpleadosMouseClicked
        // TODO add your handling code here:
        // 1. Obtener la fila seleccionada por el usuario (Paso 3 del PDF)
    int fila = tablaEmpleados.getSelectedRow();
    
    // Si el usuario seleccionó una fila válida...
    if (fila != -1) {
        // 2. Extraer los datos de la fila (Paso 4 del PDF)
        String id = tablaEmpleados.getValueAt(fila, 0).toString();
        String nombre = tablaEmpleados.getValueAt(fila, 1).toString();
        String departamento = tablaEmpleados.getValueAt(fila, 2).toString();
        
        // 3. Pasarle los datos a los JTextField correspondientes
        txtId.setText(id);
        txtNombre.setText(nombre);
        txtDepartamento.setText(departamento);
    }
    }//GEN-LAST:event_tablaEmpleadosMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new VentanaPrincipal().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnModificar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablaEmpleados;
    private javax.swing.JTextField txtDepartamento;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtNombre;
    // End of variables declaration//GEN-END:variables
}
